version: "3.7"
services:
  caddy:
    image: caddy:2.1.1-alpine
    volumes:
      - ./web/source:/var/www
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddydata:/data
      - caddyconfig:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  web:
    build: web
    volumes:
      - ./web/source:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
  caddydata:
  caddyconfig:
